- name: check if ppolicy is part of the schema
  shell: ldapsearch -Y EXTERNAL -H ldapi:/// -s sub
         -b cn=config objectclass=olcSchemaConfig | grep ppolicy
  register: ppolicy_out
  ignore_errors: yes
  changed_when: False

- name: add password policy schema
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f  /etc/ldap/schema/ppolicy.ldif
  when: ppolicy_out.stdout.count("ppolicy,") < 1

# Ignore error if ldap return code is 68 - LDAP_ALREADY_EXISTS
- name: create policy container
  shell: ldapadd -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} 
         -f {{ openldap.config_dir }}/ppolicy_container.ldif
  register: policy_command
  failed_when: policy_command.rc not in [0, 68]

- name: check if ppolicy module is registered
  shell: ldapsearch -Y EXTERNAL -H ldapi:/// -s sub 
         -b olcDatabase={1}hdb,cn=config objectclass=olcPPolicyConfig
  register: pm_out
  ignore_errors: yes
  changed_when: False

- name: add password policy module
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ openldap.config_dir }}/ppolicy_module.ldif
  when: pm_out.stdout.count(",ou={{ openldap.password_policy_ou }}") < 1

# Ignore error if ldap return code is 68 - LDAP_ALREADY_EXISTS
- name: add default policy
  shell: ldapadd -x -D {{openldap.root_dn }} -w {{ openldap.root_password }} 
         -f {{ openldap.config_dir }}/password_policy.ldif
  register: default_policy
  failed_when: default_policy.rc not in [0, 68]

# Ignore error if ldap return code is 68 - LDAP_ALREADY_EXISTS
- name: add empty policy 
  shell: ldapadd -x -D {{openldap.root_dn }} -w {{ openldap.root_password }}
         -f {{ openldap.config_dir }}/empty_password_policy.ldif
  register: empty_policy
  failed_when: empty_policy.rc not in [0, 68]

#TODO: Install from repo its uploaded there

- name: copy the deb to a temp directory
  copy: src=check_password/{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ ansible_userspace_bits }}-openldap-password-checker-1.0-1.deb
        dest=/tmp/openldap-password-checker-1.0-1.deb

- name: install checker from the package
  shell: dpkg -i /tmp/openldap-password-checker-1.0-1.deb

#END TODO Install from repo its uploaded there

# Ignore error if ldap return code is 20 - LDAP_TYPE_OR_VALUE_EXISTS
- name: add check_password ldif into ldap
  command: /usr/bin/ldapmodify -x -D {{ openldap.root_dn }} 
           -w {{ openldap.root_password }} -f {{ openldap.config_dir }}/add_passwd_config.ldif
  register: check_pass
  failed_when: check_pass.rc not in [0, 20]

- name: create openldap password config directory
  file: path="{{openldap.pp_config_dir}}"
        state=directory
        mode=0755

- name: create check_password config
  template: src=".{{openldap.pp_config_dir}}/check_password.conf"
            dest={{openldap.pp_config_dir}}/check_password.conf


- name: Create password policy utility script
  template: src=".{{openldap.pp_config_dir}}/password_policy_util.sh"
            dest="{{openldap.pp_config_dir}}/password_policy_util.sh"
            owner=root
            group=root
            mode=0700

